export const orders = [
  {
    id: 1,
    code: "#GC092921",
    status: "PENDING",
    date: "٤ أكتوبر ٢٠٢٥ - ٤ عصراً",
    total: 350,
    items: [
      {
        id: 1,
        name: "Blushora Skin Lotion",
        count: 3,
        price: 350,
        image: "https://picsum.photos/200",
      },
      {
        id: 2,
        name: "Aloe Vera Gel",
        count: 2,
        price: 250,
        image: "https://picsum.photos/200",
      },
      {
        id: 3,
        name: "Vitamin C Serum",
        count: 1,
        price: 150,
        image: "https://picsum.photos/200",
      },
      {
        id: 4,
        name: "Vitamin C Serum",
        count: 1,
        price: 150,
        image: "https://picsum.photos/200",
      },
      {
        id: 5,
        name: "Vitamin C Serum",
        count: 1,
        price: 150,
        image: "https://picsum.photos/200",
      },
      {
        id: 6,
        name: "Vitamin C Serum",
        count: 1,
        price: 150,
        image: "https://picsum.photos/200",
      },
      {
        id: 7,
        name: "Vitamin C Serum",
        count: 1,
        price: 150,
        image: "https://picsum.photos/200",
      },
    ],
  },
  {
    id: 2,
    code: "#GC092922",
    status: "CONFIRMED",
    date: "٥ أكتوبر ٢٠٢٥ - ٣ عصراً",
    total: 450,
    items: [
      {
        id: 1,
        name: "Skin Care Set",
        count: 2,
        price: 450,
        image: "https://picsum.photos/200",
      },
      {
        id: 2,
        name: "Coconut Oil",
        count: 1,
        price: 120,
        image: "https://picsum.photos/200",
      },
    ],
  },
  {
    id: 3,
    code: "#GC092923",
    status: "SHIPPED",
    date: "٦ أكتوبر ٢٠٢٥ - ٢ ظهراً",
    total: 550,
    items: [
      {
        id: 1,
        name: "Glow Cream",
        count: 1,
        price: 550,
        image: "https://picsum.photos/200",
      },
      {
        id: 2,
        name: "Natural Soap",
        count: 3,
        price: 180,
        image: "https://picsum.photos/200",
      },
    ],
  },
  {
    id: 4,
    code: "#GC092924",
    status: "COMPLETED",
    date: "٧ أكتوبر ٢٠٢٥ - ٦ مساءً",
    total: 870,
    items: [
      {
        id: 1,
        name: "Herbal Shampoo",
        count: 2,
        price: 320,
        image: "https://picsum.photos/200",
      },
      {
        id: 2,
        name: "Hair Mask",
        count: 1,
        price: 250,
        image: "https://picsum.photos/200",
      },
      {
        id: 3,
        name: "Rose Water",
        count: 2,
        price: 300,
        image: "https://picsum.photos/200",
      },
    ],
  },
  {
    id: 5,
    code: "#GC092924",
    status: "CANCELLED",
    date: "٧ أكتوبر ٢٠٢٥ - ٦ مساءً",
    total: 870,
    items: [
      {
        id: 1,
        name: "Herbal Shampoo",
        count: 2,
        price: 320,
        image: "https://picsum.photos/200",
      },
      {
        id: 2,
        name: "Hair Mask",
        count: 1,
        price: 250,
        image: "https://picsum.photos/200",
      },
      {
        id: 3,
        name: "Rose Water",
        count: 2,
        price: 300,
        image: "https://picsum.photos/200",
      },
    ],
  },
];
